USE [integrationdb]
GO
/****** Object:  Table [dbo].[IntegrationMaster]    Script Date: 1/15/2026 7:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IntegrationMaster](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IntegrationName] [varchar](50) NOT NULL,
	[IntegrationType] [varchar](20) NOT NULL,
	[Market] [varchar](10) NOT NULL,
	[LegalEntity] [varchar](20) NOT NULL,
	[Environment] [varchar](10) NOT NULL,
	[TransformationFunction] [varchar](150) NOT NULL,
	[ProcessingLayer] [varchar](50) NULL,
	[Dynamics] [varchar](50) NULL,
	[BYOL] [varchar](50) NULL,
	[CommonUpload] [varchar](255) NULL,
	[FileSize] [bigint] NULL,
	[FDDLink] [varchar](1000) NULL,
	[TDDLink] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[IntegrationMaster] ON 
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (1, N'AutomasterFT', N'Inbound', N'EA', N'HK1', N'TEST', N'd365-func-ft-ea-test-001', N'kvd365processeatest', N'AutomasterFT-HK1-12323', N'datalakeeatest001', N'func-d365-upload-ea-test-001', 1145757, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (2, N'AutomasterFT', N'Inbound', N'EA', N'HK1', N'UAT', N'd365-func-ft-ea-uat-001', N'kvd365processeauat', N'AutomasterFT-HK1-12323', N'datalakeeauat002', N'func-d365-upload-ea-uat-002', 1353914, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (3, N'AutomasterFT', N'Inbound', N'EA', N'HK1', N'PROD', N'd365-func-ft-ea-prod-001', N'kvd365processeaprod', N'AutomasterFT-HK1-12323', N'datalakeeaprod003', N'func-d365-upload-ea-prod-003', 1346996, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (4, N'AutomasterFT', N'Inbound', N'EA', N'JP1', N'TEST', N'd365-func-ft-ea-test-001', N'kvd365processeatest', N'AutomasterFT-JP1-12323', N'datalakeeatest001', N'func-d365-upload-ea-test-001', 1219026, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (5, N'AutomasterFT', N'Inbound', N'EA', N'JP1', N'UAT', N'd365-func-ft-ea-uat-001', N'kvd365processeauat', N'AutomasterFT-JP1-12323', N'datalakeeauat002', N'func-d365-upload-ea-uat-002', 1408750, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (6, N'AutomasterFT', N'Inbound', N'EA', N'JP1', N'PROD', N'd365-func-ft-ea-prod-001', N'kvd365processeaprod', N'AutomasterFT-JP1-12323', N'datalakeeaprod003', N'func-d365-upload-ea-prod-003', 1321735, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (7, N'AutomasterFT', N'Inbound', N'WE', N'EE1', N'TEST', N'd365-func-ft-we-test-001', N'kvd365processwetest', N'AutomasterFT-EE1-45678', N'datalakewetest001', N'func-d365-upload-we-test-001', 1449883, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (8, N'AutomasterFT', N'Inbound', N'WE', N'EE1', N'UAT', N'd365-func-ft-we-uat-001', N'kvd365processweuat', N'AutomasterFT-EE1-45678', N'datalakeweuat002', N'func-d365-upload-we-uat-002', 1081922, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (9, N'AutomasterFT', N'Inbound', N'WE', N'EE1', N'PROD', N'd365-func-ft-we-prod-001', N'kvd365processweprod', N'AutomasterFT-EE1-45678', N'datalakeweprod003', N'func-d365-upload-we-prod-003', 1489896, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (10, N'AutomasterFT', N'Inbound', N'WE', N'LV1', N'TEST', N'd365-func-ft-we-test-001', N'kvd365processwetest', N'AutomasterFT-LV1-45678', N'datalakewetest001', N'func-d365-upload-we-test-001', 1551864, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (11, N'AutomasterFT', N'Inbound', N'WE', N'LV1', N'UAT', N'd365-func-ft-we-uat-001', N'kvd365processweuat', N'AutomasterFT-LV1-45678', N'datalakeweuat002', N'func-d365-upload-we-uat-002', 1474345, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (12, N'AutomasterFT', N'Inbound', N'WE', N'LV1', N'PROD', N'd365-func-ft-we-prod-001', N'kvd365processweprod', N'AutomasterFT-LV1-45678', N'datalakeweprod003', N'func-d365-upload-we-prod-003', 1512903, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (13, N'AutomasterFT', N'Inbound', N'BS', N'BS1', N'TEST', N'd365-func-ft-bs-test-001', N'kvd365processbstest', N'AutomasterFT-BS1-78901', N'datalakebstest001', N'func-d365-upload-bs-test-001', 1327524, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (14, N'AutomasterFT', N'Inbound', N'BS', N'BS1', N'UAT', N'd365-func-ft-bs-uat-001', N'kvd365processbsuat', N'AutomasterFT-BS1-78901', N'datalakebsuat002', N'func-d365-upload-bs-uat-002', 1571289, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (15, N'AutomasterFT', N'Inbound', N'BS', N'BS1', N'PROD', N'd365-func-ft-bs-prod-001', N'kvd365processbsprod', N'AutomasterFT-BS1-78901', N'datalakebsprod003', N'func-d365-upload-bs-prod-003', 1133881, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD- 42947 Integration -Inbound -AUTOMASTER- FT- Baltic.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD Integration Inbound - GENERIC - FT.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (16, N'SDSIF', N'Inbound', N'EA', N'HK1', N'TEST', N'd365-func-if-ea-test-001', N'kvd365processeatest', N'SDSIF-HK1-12323', N'datalakeeatest001', N'func-d365-upload-ea-test-001', 1059975, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (17, N'SDSIF', N'Inbound', N'EA', N'HK1', N'UAT', N'd365-func-if-ea-uat-001', N'kvd365processeauat', N'SDSIF-HK1-12323', N'datalakeeauat002', N'func-d365-upload-ea-uat-002', 1463106, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (18, N'SDSIF', N'Inbound', N'EA', N'HK1', N'PROD', N'd365-func-if-ea-prod-001', N'kvd365processeaprod', N'SDSIF-HK1-12323', N'datalakeeaprod003', N'func-d365-upload-ea-prod-003', 1144905, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (19, N'SDSIF', N'Inbound', N'EA', N'KR1', N'TEST', N'd365-func-if-ea-test-001', N'kvd365processeatest', N'SDSIF-KR1-12323', N'datalakeeatest001', N'func-d365-upload-ea-test-001', 1188234, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (20, N'SDSIF', N'Inbound', N'EA', N'KR1', N'UAT', N'd365-func-if-ea-uat-001', N'kvd365processeauat', N'SDSIF-KR1-12323', N'datalakeeauat002', N'func-d365-upload-ea-uat-002', 1330251, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (21, N'SDSIF', N'Inbound', N'EA', N'KR1', N'PROD', N'd365-func-if-ea-prod-001', N'kvd365processeaprod', N'SDSIF-KR1-12323', N'datalakeeaprod003', N'func-d365-upload-ea-prod-003', 1057671, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (22, N'SDSIF', N'Inbound', N'WE', N'EE1', N'TEST', N'd365-func-if-we-test-001', N'kvd365processwetest', N'SDSIF-EE1-45678', N'datalakewetest001', N'func-d365-upload-we-test-001', 1141114, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (23, N'SDSIF', N'Inbound', N'WE', N'EE1', N'UAT', N'd365-func-if-we-uat-001', N'kvd365processweuat', N'SDSIF-EE1-45678', N'datalakeweuat002', N'func-d365-upload-we-uat-002', 1359298, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (24, N'SDSIF', N'Inbound', N'WE', N'EE1', N'PROD', N'd365-func-if-we-prod-001', N'kvd365processweprod', N'SDSIF-EE1-45678', N'datalakeweprod003', N'func-d365-upload-we-prod-003', 1509580, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (25, N'SDSIF', N'Inbound', N'WE', N'LT1', N'TEST', N'd365-func-if-we-test-001', N'kvd365processwetest', N'SDSIF-LT1-45678', N'datalakewetest001', N'func-d365-upload-we-test-001', 1400907, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (26, N'SDSIF', N'Inbound', N'WE', N'LT1', N'UAT', N'd365-func-if-we-uat-001', N'kvd365processweuat', N'SDSIF-LT1-45678', N'datalakeweuat002', N'func-d365-upload-we-uat-002', 1318129, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (27, N'SDSIF', N'Inbound', N'WE', N'LT1', N'PROD', N'd365-func-if-we-prod-001', N'kvd365processweprod', N'SDSIF-LT1-45678', N'datalakeweprod003', N'func-d365-upload-we-prod-003', 1112323, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (28, N'SDSIF', N'Inbound', N'BS', N'BS1', N'TEST', N'd365-func-ft-bs-test-001', N'kvd365processbstest', N'SDSIF-BS1-78901', N'datalakebstest001', N'func-d365-upload-bs-test-001', 1168187, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (29, N'SDSIF', N'Inbound', N'BS', N'BS1', N'UAT', N'd365-func-ft-bs-uat-001', N'kvd365processbsuat', N'SDSIF-BS1-78901', N'datalakebsuat002', N'func-d365-upload-bs-uat-002', 1522687, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (30, N'SDSIF', N'Inbound', N'BS', N'BS1', N'PROD', N'd365-func-ft-bs-prod-001', N'kvd365processbsprod', N'SDSIF-BS1-78901', N'datalakebsprod003', N'func-d365-upload-bs-prod-003', 1083202, N'https://rgintegrationmanage8c3d.blob.core.windows.net/fdd-documents/FDD 19781 Integration Inbound - SDS - IF - Benelux.docx', N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD 19781 Integration Inbound - SDS - IF.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (31, N'SALSA', N'Outbound', N'EA', N'HK1', N'TEST', N'd365-func-salsa-ea-test-001', N'kvd365processeatest', N'SALSA-HK1-12323', N'datalakeeatest001', N'func-d365-upload-ea-test-001', 3145728, NULL, N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD PARTS-338 - Integration - Inbound - SALSA - PO confirmation.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (32, N'SALSA', N'Outbound', N'EA', N'HK1', N'UAT', N'd365-func-salsa-ea-uat-001', N'kvd365processeauat', N'SALSA-HK1-12323', N'datalakeeauat002', N'func-d365-upload-ea-uat-002', 3145728, NULL, N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD PARTS-338 - Integration - Inbound - SALSA - PO confirmation.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (33, N'SALSA', N'Outbound', N'EA', N'HK1', N'PROD', N'd365-func-salsa-ea-prod-001', N'kvd365processeaprod', N'SALSA-HK1-12323', N'datalakeeaprod003', N'func-d365-upload-ea-prod-003', 3145728, NULL, N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD PARTS-338 - Integration - Inbound - SALSA - PO confirmation.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (34, N'SALSA', N'Outbound', N'WE', N'EE1', N'TEST', N'd365-func-salsa-we-test-001', N'kvd365processwetest', N'SALSA-EE1-45678', N'datalakewetest001', N'func-d365-upload-we-test-001', 3145728, NULL, N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD PARTS-338 - Integration - Inbound - SALSA - PO confirmation.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (35, N'SALSA', N'Outbound', N'WE', N'EE1', N'UAT', N'd365-func-salsa-we-uat-001', N'kvd365processweuat', N'SALSA-EE1-45678', N'datalakeweuat002', N'func-d365-upload-we-uat-002', 3145728, NULL, N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD PARTS-338 - Integration - Inbound - SALSA - PO confirmation.docx')
GO
INSERT [dbo].[IntegrationMaster] ([Id], [IntegrationName], [IntegrationType], [Market], [LegalEntity], [Environment], [TransformationFunction], [ProcessingLayer], [Dynamics], [BYOL], [CommonUpload], [FileSize], [FDDLink], [TDDLink]) VALUES (36, N'SALSA', N'Outbound', N'WE', N'EE1', N'PROD', N'd365-func-salsa-we-prod-001', N'kvd365processweprod', N'SALSA-EE1-45678', N'datalakeweprod003', N'func-d365-upload-we-prod-003', 3145728, NULL, N'https://rgintegrationmanage8c3d.blob.core.windows.net/tdd-documents/TDD PARTS-338 - Integration - Inbound - SALSA - PO confirmation.docx')
GO
SET IDENTITY_INSERT [dbo].[IntegrationMaster] OFF
GO
